name: Build and upload binaries to release

on:
  push:

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.triple.os }}
    strategy:
      matrix:
        triple:
          # aarch64 android
          - {
              os: ubuntu-latest,
              target: aarch64-linux-android,
              cross: true,
              artifact_name: aarch64-linux-android.zip
            }
          # armv7a android
          - {
              os: ubuntu-latest,
              target: armv7a-linux-androideabi,
              cross: true,
              artifact_name: armv7a-linux-androideabi.zip
            }
          # i686 android
          - {
              os: ubuntu-latest,
              target: i686-linux-android,
              cross: true,
              artifact_name: i686-linux-android.zip
            }
          # x86_64 android
          - {
              os: ubuntu-latest,
              target: x86_64-linux-android,
              cross: true,
              artifact_name: x86_64-linux-android.zip
            }
          # arm64 ios
          - {
              os: macos-latest,
              target: arm64-ios,
              artifact_name: arm64-ios.zip
            }
          # x86_64 ios
          - {
              os: macos-latest,
              target: x86_64-ios,
              artifact_name: x86_64-ios.zip
            }
          # x86_64 macos
          - {
              os: macos-latest,
              target: x86_64-osx,
              artifact_name: x86_64-osx.zip
            }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        if: matrix.triple.os == 'ubuntu-latest'
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set up Android
        if: matrix.triple.os == 'ubuntu-latest'
        run: ./android-linux-setup.sh
      - name: Set up Xcode
        if: matrix.triple.os == 'macos-latest'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'
      - name: Download gmp
        run: cd build && ./download.sh
      - name: Build
        run: |
          TARGET=${{ matrix.triple.target }}
          case $TARGET in
            "aarch64-linux-android" | "armv7a-linux-androideabi" | "i686-linux-android" | "x86_64-linux-android")
              cd build
              ./linux-build.sh $TARGET
              sudo apt install tree
              tree $HOME/$TARGET
              zip -r /tmp/${{ matrix.triple.artifact_name }} $HOME/$TARGET
              ;;
            *)
              cd build
              ./macos-build.sh $TARGET
              cd gmp
              zip -r /tmp/${{ matrix.triple.artifact_name }} gmplib-$TARGET
              ;;
          esac
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/${{ matrix.triple.artifact_name }}
          asset_name: ${{ matrix.triple.artifact_name }}
          tag: 6.2.1
          overwrite: true
